using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace cb0t
{
    class Emoji_Objects : UserControl
    {
        private ToolTip tip { get; set; }

        public void Populate(EventHandler callback)
        {
            this.tip = new ToolTip();

            EmojiMenuShortcutItem[] items = new EmojiMenuShortcutItem[230];
            items[0] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57229", Shortcut = "🎍", Description = "Pine Decoration" };
            items[1] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56477", Shortcut = "💝", Description = "Heart With Ribbon" };
            items[2] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57230", Shortcut = "🎎", Description = "Japanese Dolls" };
            items[3] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57234", Shortcut = "🎒", Description = "School Satchel" };
            items[4] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57235", Shortcut = "🎓", Description = "Graduation Cap" };
            items[5] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57231", Shortcut = "🎏", Description = "Carp Streamer" };
            items[6] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57222", Shortcut = "🎆", Description = "Fireworks" };
            items[7] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57223", Shortcut = "🎇", Description = "Firework Sparkler" };
            items[8] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57232", Shortcut = "🎐", Description = "Wind Chime" };
            items[9] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57233", Shortcut = "🎑", Description = "Moon Viewing Ceremony" };
            items[10] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57219", Shortcut = "🎃", Description = "Jack-O-Lantern" };
            items[11] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56443", Shortcut = "👻", Description = "Ghost" };
            items[12] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57221", Shortcut = "🎅", Description = "Father Christmas" };
            items[13] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57220", Shortcut = "🎄", Description = "Christmas Tree" };
            items[14] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57217", Shortcut = "🎁", Description = "Wrapped Present" };
            items[15] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57227", Shortcut = "🎋", Description = "Tanabata Tree" };
            items[16] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57225", Shortcut = "🎉", Description = "Party Popper" };
            items[17] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57226", Shortcut = "🎊", Description = "Confetti Ball" };
            items[18] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57224", Shortcut = "🎈", Description = "Balloon" };
            items[19] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57228", Shortcut = "🎌", Description = "Crossed Flags" };
            items[20] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56622", Shortcut = "🔮", Description = "Crystal Ball" };
            items[21] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57253", Shortcut = "🎥", Description = "Movie Camera" };
            items[22] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56567", Shortcut = "📷", Description = "Camera" };
            items[23] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56569", Shortcut = "📹", Description = "Video Camera" };
            items[24] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56572", Shortcut = "📼", Description = "Videocassette" };
            items[25] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56511", Shortcut = "💿", Description = "Optical Disc" };
            items[26] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56512", Shortcut = "📀", Description = "DVD" };
            items[27] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56509", Shortcut = "💽", Description = "Minidisc" };
            items[28] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56510", Shortcut = "💾", Description = "Floppy Disk" };
            items[29] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56507", Shortcut = "💻", Description = "Personal Computer" };
            items[30] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56561", Shortcut = "📱", Description = "Mobile Phone" };
            items[31] = new EmojiMenuShortcutItem { SurrogateSequence = "9742", Shortcut = "☎", Description = "Black Telephone" };
            items[32] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56542", Shortcut = "📞", Description = "Telephone Receiver" };
            items[33] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56543", Shortcut = "📟", Description = "Pager" };
            items[34] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56544", Shortcut = "📠", Description = "Fax Machine" };
            items[35] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56545", Shortcut = "📡", Description = "Satellite Antenna" };
            items[36] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56570", Shortcut = "📺", Description = "Television" };
            items[37] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56571", Shortcut = "📻", Description = "Radio" };
            items[38] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56586", Shortcut = "🔊", Description = "Speaker With Three Sound Waves" };
            items[39] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56585", Shortcut = "🔉", Description = "Speaker With One Sound Wave" };
            items[40] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56584", Shortcut = "🔈", Description = "Speaker" };
            items[41] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56583", Shortcut = "🔇", Description = "Speaker With Cancellation Stroke" };
            items[42] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56596", Shortcut = "🔔", Description = "Bell" };
            items[43] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56597", Shortcut = "🔕", Description = "Bell With Cancellation Stroke" };
            items[44] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56546", Shortcut = "📢", Description = "Public Address Loudspeaker" };
            items[45] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56547", Shortcut = "📣", Description = "Cheering Megaphone" };
            items[46] = new EmojiMenuShortcutItem { SurrogateSequence = "9203", Shortcut = "⏳", Description = "Hourglass With Flowing Sand" };
            items[47] = new EmojiMenuShortcutItem { SurrogateSequence = "8987", Shortcut = "⌛", Description = "Hourglass" };
            items[48] = new EmojiMenuShortcutItem { SurrogateSequence = "9200", Shortcut = "⏰", Description = "Alarm Clock" };
            items[49] = new EmojiMenuShortcutItem { SurrogateSequence = "8986", Shortcut = "⌚", Description = "Watch" };
            items[50] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56595", Shortcut = "🔓", Description = "Open Lock" };
            items[51] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56594", Shortcut = "🔒", Description = "Lock" };
            items[52] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56591", Shortcut = "🔏", Description = "Lock With Ink Pen" };
            items[53] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56592", Shortcut = "🔐", Description = "Closed Lock With Key" };
            items[54] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56593", Shortcut = "🔑", Description = "Key" };
            items[55] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56590", Shortcut = "🔎", Description = "Right-Pointing Magnifying Glass" };
            items[56] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56481", Shortcut = "💡", Description = "Electric Light Bulb" };
            items[57] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56614", Shortcut = "🔦", Description = "Electric Torch" };
            items[58] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56582", Shortcut = "🔆", Description = "High Brightness Symbol" };
            items[59] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56581", Shortcut = "🔅", Description = "Low Brightness Symbol" };
            items[60] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56588", Shortcut = "🔌", Description = "Electric Plug" };
            items[61] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56587", Shortcut = "🔋", Description = "Battery" };
            items[62] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56589", Shortcut = "🔍", Description = "Left-Pointing Magnifying Glass" };
            items[63] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 57025", Shortcut = "🛁", Description = "Bathtub" };
            items[64] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 57024", Shortcut = "🛀", Description = "Bath" };
            items[65] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 57023", Shortcut = "🚿", Description = "Shower" };
            items[66] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 57021", Shortcut = "🚽", Description = "Toilet" };
            items[67] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56615", Shortcut = "🔧", Description = "Wrench" };
            items[68] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56617", Shortcut = "🔩", Description = "Nut And Bolt" };
            items[69] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56616", Shortcut = "🔨", Description = "Hammer" };
            items[70] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 57002", Shortcut = "🚪", Description = "Door" };
            items[71] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 57004", Shortcut = "🚬", Description = "Smoking Symbol" };
            items[72] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56483", Shortcut = "💣", Description = "Bomb" };
            items[73] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56619", Shortcut = "🔫", Description = "Pistol" };
            items[74] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56618", Shortcut = "🔪", Description = "Hocho" };
            items[75] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56458", Shortcut = "💊", Description = "Pill" };
            items[76] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56457", Shortcut = "💉", Description = "Syringe" };
            items[77] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56496", Shortcut = "💰", Description = "Money Bag" };
            items[78] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56500", Shortcut = "💴", Description = "Banknote With Yen Sign" };
            items[79] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56501", Shortcut = "💵", Description = "Banknote With Dollar Sign" };
            items[80] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56503", Shortcut = "💷", Description = "Banknote With Pound Sign" };
            items[81] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56502", Shortcut = "💶", Description = "Banknote With Euro Sign" };
            items[82] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56499", Shortcut = "💳", Description = "Credit Card" };
            items[83] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56504", Shortcut = "💸", Description = "Money With Wings" };
            items[84] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56562", Shortcut = "📲", Description = "Mobile Phone With Rightwards Arrow At Left" };
            items[85] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56551", Shortcut = "📧", Description = "E-Mail Symbol" };
            items[86] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56549", Shortcut = "📥", Description = "Inbox Tray" };
            items[87] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56548", Shortcut = "📤", Description = "Outbox Tray" };
            items[88] = new EmojiMenuShortcutItem { SurrogateSequence = "9993", Shortcut = "✉", Description = "Envelope" };
            items[89] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56553", Shortcut = "📩", Description = "Envelope With Downwards Arrow Above" };
            items[90] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56552", Shortcut = "📨", Description = "Incoming Envelope" };
            items[91] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56559", Shortcut = "📯", Description = "Postal Horn" };
            items[92] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56555", Shortcut = "📫", Description = "Closed Mailbox With Raised Flag" };
            items[93] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56554", Shortcut = "📪", Description = "Closed Mailbox With Lowered Flag" };
            items[94] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56556", Shortcut = "📬", Description = "Open Mailbox With Raised Flag" };
            items[95] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56557", Shortcut = "📭", Description = "Open Mailbox With Lowered Flag" };
            items[96] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56558", Shortcut = "📮", Description = "Postbox" };
            items[97] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56550", Shortcut = "📦", Description = "Package" };
            items[98] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56541", Shortcut = "📝", Description = "Memo" };
            items[99] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56516", Shortcut = "📄", Description = "Page Facing Up" };
            items[100] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56515", Shortcut = "📃", Description = "Page With Curl" };
            items[101] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56529", Shortcut = "📑", Description = "Bookmark Tabs" };
            items[102] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56522", Shortcut = "📊", Description = "Bar Chart" };
            items[103] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56520", Shortcut = "📈", Description = "Chart With Upwards Trend" };
            items[104] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56521", Shortcut = "📉", Description = "Chart With Downwards Trend" };
            items[105] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56540", Shortcut = "📜", Description = "Scroll" };
            items[106] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56523", Shortcut = "📋", Description = "Clipboard" };
            items[107] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56517", Shortcut = "📅", Description = "Calendar" };
            items[108] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56518", Shortcut = "📆", Description = "Tear-Off Calendar" };
            items[109] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56519", Shortcut = "📇", Description = "Card Index" };
            items[110] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56513", Shortcut = "📁", Description = "File Folder" };
            items[111] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56514", Shortcut = "📂", Description = "Open File Folder" };
            items[112] = new EmojiMenuShortcutItem { SurrogateSequence = "9986", Shortcut = "✂", Description = "Black Scissors" };
            items[113] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56524", Shortcut = "📌", Description = "Pushpin" };
            items[114] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56526", Shortcut = "📎", Description = "Paperclip" };
            items[115] = new EmojiMenuShortcutItem { SurrogateSequence = "10002", Shortcut = "✒", Description = "Black Nib" };
            items[116] = new EmojiMenuShortcutItem { SurrogateSequence = "9999", Shortcut = "✏", Description = "Pencil" };
            items[117] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56527", Shortcut = "📏", Description = "Straight Ruler" };
            items[118] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56528", Shortcut = "📐", Description = "Triangular Ruler" };
            items[119] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56533", Shortcut = "📕", Description = "Closed Book" };
            items[120] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56535", Shortcut = "📗", Description = "Green Book" };
            items[121] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56536", Shortcut = "📘", Description = "Blue Book" };
            items[122] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56537", Shortcut = "📙", Description = "Orange Book" };
            items[123] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56531", Shortcut = "📓", Description = "Notebook" };
            items[124] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56532", Shortcut = "📔", Description = "Notebook With Decorative Cover" };
            items[125] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56530", Shortcut = "📒", Description = "Ledger" };
            items[126] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56538", Shortcut = "📚", Description = "Books" };
            items[127] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56534", Shortcut = "📖", Description = "Open Book" };
            items[128] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56598", Shortcut = "🔖", Description = "Bookmark" };
            items[129] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56539", Shortcut = "📛", Description = "Name Badge" };
            items[130] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56620", Shortcut = "🔬", Description = "Microscope" };
            items[131] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56621", Shortcut = "🔭", Description = "Telescope  " };
            items[132] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56560", Shortcut = "📰", Description = "Newspaper" };
            items[133] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57256", Shortcut = "🎨", Description = "Artist Palette" };
            items[134] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57260", Shortcut = "🎬", Description = "Clapper Board" };
            items[135] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57252", Shortcut = "🎤", Description = "Microphone" };
            items[136] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57255", Shortcut = "🎧", Description = "Headphone" };
            items[137] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57276", Shortcut = "🎼", Description = "Musical Score" };
            items[138] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57269", Shortcut = "🎵", Description = "Musical Note" };
            items[139] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57270", Shortcut = "🎶", Description = "Multiple Musical Notes" };
            items[140] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57273", Shortcut = "🎹", Description = "Musical Keyboard" };
            items[141] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57275", Shortcut = "🎻", Description = "Violin" };
            items[142] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57274", Shortcut = "🎺", Description = "Trumpet" };
            items[143] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57271", Shortcut = "🎷", Description = "Saxophone" };
            items[144] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57272", Shortcut = "🎸", Description = "Guitar" };
            items[145] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 56446", Shortcut = "👾", Description = "Alien Monster" };
            items[146] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57262", Shortcut = "🎮", Description = "Video Game" };
            items[147] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 56527", Shortcut = "🃏", Description = "Playing Card Black Joker" };
            items[148] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57268", Shortcut = "🎴", Description = "Flower Playing Cards" };
            items[149] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 56324", Shortcut = "🀄", Description = "Mahjong Tile Red Dragon" };
            items[150] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57266", Shortcut = "🎲", Description = "Game Die" };
            items[151] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57263", Shortcut = "🎯", Description = "Direct Hit" };
            items[152] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57288", Shortcut = "🏈", Description = "American Football" };
            items[153] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57280", Shortcut = "🏀", Description = "Basketball And Hoop" };
            items[154] = new EmojiMenuShortcutItem { SurrogateSequence = "9917", Shortcut = "⚽", Description = "Soccer Ball" };
            items[155] = new EmojiMenuShortcutItem { SurrogateSequence = "9918", Shortcut = "⚾", Description = "Baseball" };
            items[156] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57278", Shortcut = "🎾", Description = "Tennis Racquet And Ball" };
            items[157] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57265", Shortcut = "🎱", Description = "Billiards" };
            items[158] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57289", Shortcut = "🏉", Description = "Rugby Football" };
            items[159] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57267", Shortcut = "🎳", Description = "Bowling" };
            items[160] = new EmojiMenuShortcutItem { SurrogateSequence = "9971", Shortcut = "⛳", Description = "Flag In Hole" };
            items[161] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 57013", Shortcut = "🚵", Description = "Mountain Bicyclist" };
            items[162] = new EmojiMenuShortcutItem { SurrogateSequence = "55357 57012", Shortcut = "🚴", Description = "Bicyclist" };
            items[163] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57281", Shortcut = "🏁", Description = "Chequered Flag" };
            items[164] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57287", Shortcut = "🏇", Description = "Horse Racing" };
            items[165] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57286", Shortcut = "🏆", Description = "Trophy" };
            items[166] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57279", Shortcut = "🎿", Description = "Ski And Ski Boot" };
            items[167] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57282", Shortcut = "🏂", Description = "Snowboarder" };
            items[168] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57290", Shortcut = "🏊", Description = "Swimmer" };
            items[169] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57284", Shortcut = "🏄", Description = "Surfer" };
            items[170] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57251", Shortcut = "🎣", Description = "Fishing Pole And Fish" };
            items[171] = new EmojiMenuShortcutItem { SurrogateSequence = "9749", Shortcut = "☕", Description = "Hot Beverage" };
            items[172] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57205", Shortcut = "🍵", Description = "Teacup Without Handle" };
            items[173] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57206", Shortcut = "🍶", Description = "Sake Bottle And Cup" };
            items[174] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57212", Shortcut = "🍼", Description = "Baby Bottle" };
            items[175] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57210", Shortcut = "🍺", Description = "Beer Mug" };
            items[176] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57211", Shortcut = "🍻", Description = "Clinking Beer Mugs" };
            items[177] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57208", Shortcut = "🍸", Description = "Cocktail Glass" };
            items[178] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57209", Shortcut = "🍹", Description = "Tropical Drink" };
            items[179] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57207", Shortcut = "🍷", Description = "Wine Glass" };
            items[180] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57204", Shortcut = "🍴", Description = "Fork And Knife" };
            items[181] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57173", Shortcut = "🍕", Description = "Slice Of Pizza" };
            items[182] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57172", Shortcut = "🍔", Description = "Hamburger" };
            items[183] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57183", Shortcut = "🍟", Description = "French Fries" };
            items[184] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57175", Shortcut = "🍗", Description = "Poultry Leg" };
            items[185] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57174", Shortcut = "🍖", Description = "Meat On Bone" };
            items[186] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57181", Shortcut = "🍝", Description = "Spaghetti" };
            items[187] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57179", Shortcut = "🍛", Description = "Curry And Rice" };
            items[188] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57188", Shortcut = "🍤", Description = "Fried Shrimp" };
            items[189] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57201", Shortcut = "🍱", Description = "Bento Box" };
            items[190] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57187", Shortcut = "🍣", Description = "Sushi" };
            items[191] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57189", Shortcut = "🍥", Description = "Fish Cake With Swirl Design" };
            items[192] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57177", Shortcut = "🍙", Description = "Rice Ball" };
            items[193] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57176", Shortcut = "🍘", Description = "Rice Cracker" };
            items[194] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57178", Shortcut = "🍚", Description = "Cooked Rice" };
            items[195] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57180", Shortcut = "🍜", Description = "Steaming Bowl" };
            items[196] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57202", Shortcut = "🍲", Description = "Pot Of Food" };
            items[197] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57186", Shortcut = "🍢", Description = "Oden" };
            items[198] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57185", Shortcut = "🍡", Description = "Dango" };
            items[199] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57203", Shortcut = "🍳", Description = "Cooking" };
            items[200] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57182", Shortcut = "🍞", Description = "Bread" };
            items[201] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57193", Shortcut = "🍩", Description = "Doughnut" };
            items[202] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57198", Shortcut = "🍮", Description = "Custard" };
            items[203] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57190", Shortcut = "🍦", Description = "Soft Ice Cream" };
            items[204] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57192", Shortcut = "🍨", Description = "Ice Cream" };
            items[205] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57191", Shortcut = "🍧", Description = "Shaved Ice" };
            items[206] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57218", Shortcut = "🎂", Description = "Birthday Cake" };
            items[207] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57200", Shortcut = "🍰", Description = "Shortcake" };
            items[208] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57194", Shortcut = "🍪", Description = "Cookie" };
            items[209] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57195", Shortcut = "🍫", Description = "Chocolate Bar" };
            items[210] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57196", Shortcut = "🍬", Description = "Candy" };
            items[211] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57197", Shortcut = "🍭", Description = "Lollipop" };
            items[212] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57199", Shortcut = "🍯", Description = "Honey Pot" };
            items[213] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57166", Shortcut = "🍎", Description = "Red Apple" };
            items[214] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57167", Shortcut = "🍏", Description = "Green Apple" };
            items[215] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57162", Shortcut = "🍊", Description = "Tangerine" };
            items[216] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57163", Shortcut = "🍋", Description = "Lemon" };
            items[217] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57170", Shortcut = "🍒", Description = "Cherries" };
            items[218] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57159", Shortcut = "🍇", Description = "Grapes" };
            items[219] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57161", Shortcut = "🍉", Description = "Watermelon" };
            items[220] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57171", Shortcut = "🍓", Description = "Strawberry" };
            items[221] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57169", Shortcut = "🍑", Description = "Peach" };
            items[222] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57160", Shortcut = "🍈", Description = "Melon" };
            items[223] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57164", Shortcut = "🍌", Description = "Banana" };
            items[224] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57168", Shortcut = "🍐", Description = "Pear" };
            items[225] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57165", Shortcut = "🍍", Description = "Pineapple" };
            items[226] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57184", Shortcut = "🍠", Description = "Roasted Sweet Potato" };
            items[227] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57158", Shortcut = "🍆", Description = "Aubergine" };
            items[228] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57157", Shortcut = "🍅", Description = "Tomato" };
            items[229] = new EmojiMenuShortcutItem { SurrogateSequence = "55356 57149", Shortcut = "🌽", Description = "Ear Of Maize" };

            for (int i = 0; i < items.Length; i++)
            {
                PictureBox pic = new PictureBox();
                pic.BackColor = Color.White;
                pic.Size = new Size(24, 24);
                int per_line = 8;
                pic.Location = new Point(1 + ((i % per_line) * 24) + (i % per_line), 1 + ((i / per_line) * 24) + (i / per_line));
                pic.Cursor = Cursors.Hand;
                pic.Tag = items[i];
                pic.MouseHover += this.pic_MouseHover;
                pic.Click += callback;
                EmojiItem item = Emoji.EmojiFromSurrogate(items[i].SurrogateSequence);
                pic.ImageLocation = Path.Combine(Settings.AppPath, "emoji", "at24", item.FileName);
                pic.SizeMode = PictureBoxSizeMode.CenterImage;
                this.Controls.Add(pic);
            }
        }

        private void pic_MouseHover(object sender, EventArgs e)
        {
            PictureBox pb = (PictureBox)sender;
            this.tip.SetToolTip(pb, ((EmojiMenuShortcutItem)pb.Tag).Description);
        }
    }
}
